name: Lint web portal

on:
  push:
    branches:
      - main
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  run_lint:
    defaults:
      run:
        working-directory: ./frontend
    name: Run Eslint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Configure node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: ./frontend/yarn.lock

      - name: Install dependencies
        run: |
          yarn

      - name: Run linter
        run: |
          yarn lint
